#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['perky']

package_data = \
{'': ['*']}

install_requires = \
['big >= 0.14']

setup(name='perky',
      version='0.10',
      description='A simple, Pythonic file format.  Provides load, loads, dump, and',
      author='Larry Hastings',
      author_email='larry@hastings.org',
      url='https://github.com/larryhastings/perky/',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
